/**
 * Environment variable management for .env files.
 * Provides safe read/write operations with validation.
 */

import { existsSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { logger } from '@orchestrator/shared';

export interface EnvVar {
  key: string;
  value: string;
  line?: number;
}

/**
 * Parse a .env file into key-value pairs.
 */
export function parseEnvFile(filePath: string): Map<string, EnvVar> {
  const envVars = new Map<string, EnvVar>();

  if (!existsSync(filePath)) {
    return envVars;
  }

  const content = readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');

  lines.forEach((line, index) => {
    const trimmed = line.trim();

    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith('#')) {
      return;
    }

    // Parse KEY=VALUE
    const equalIndex = trimmed.indexOf('=');
    if (equalIndex === -1) {
      return;
    }

    const key = trimmed.substring(0, equalIndex).trim();
    let value = trimmed.substring(equalIndex + 1).trim();

    // Remove surrounding quotes
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    envVars.set(key, { key, value, line: index + 1 });
  });

  return envVars;
}

/**
 * Get an environment variable from a .env file.
 */
export function getEnvVar(filePath: string, key: string): string | undefined {
  const envVars = parseEnvFile(filePath);
  return envVars.get(key)?.value;
}

/**
 * Set an environment variable in a .env file.
 * Creates the file if it doesn't exist.
 * Updates the value if the key already exists.
 */
export function setEnvVar(filePath: string, key: string, value: string): void {
  const absolutePath = resolve(filePath);

  if (!existsSync(absolutePath)) {
    // Create new file with the variable
    writeFileSync(absolutePath, `# Orchestrator Environment\n${key}=${value}\n`, 'utf-8');
    logger.debug({ path: absolutePath }, 'Created new .env file');
    return;
  }

  const content = readFileSync(absolutePath, 'utf-8');
  const lines = content.split('\n');
  let found = false;

  const newLines = lines.map((line) => {
    const trimmed = line.trim();

    // Check if this line sets our key
    if (trimmed.startsWith(`${key}=`)) {
      found = true;
      return `${key}=${value}`;
    }

    return line;
  });

  if (!found) {
    // Append the new variable
    if (newLines[newLines.length - 1] !== '') {
      newLines.push('');
    }
    newLines.push(`${key}=${value}`);
  }

  writeFileSync(absolutePath, newLines.join('\n'), 'utf-8');
  logger.debug({ key, path: absolutePath }, 'Updated environment variable');
}

/**
 * Set multiple environment variables at once.
 */
export function setEnvVars(filePath: string, vars: Record<string, string>): void {
  for (const [key, value] of Object.entries(vars)) {
    setEnvVar(filePath, key, value);
  }
}

/**
 * Delete an environment variable from a .env file.
 */
export function deleteEnvVar(filePath: string, key: string): boolean {
  if (!existsSync(filePath)) {
    return false;
  }

  const content = readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  let found = false;

  const newLines = lines.filter((line) => {
    const trimmed = line.trim();
    if (trimmed.startsWith(`${key}=`)) {
      found = true;
      return false;
    }
    return true;
  });

  if (found) {
    writeFileSync(filePath, newLines.join('\n'), 'utf-8');
  }

  return found;
}

/**
 * Get all environment variables from a .env file.
 */
export function getAllEnvVars(filePath: string): Record<string, string> {
  const envVars = parseEnvFile(filePath);
  const result: Record<string, string> = {};

  for (const [key, envVar] of envVars) {
    result[key] = envVar.value;
  }

  return result;
}

/**
 * Check if a .env file exists.
 */
export function envFileExists(filePath: string): boolean {
  return existsSync(resolve(filePath));
}

/**
 * Create a .env file from a template.
 */
export function createEnvTemplate(filePath: string, template: Record<string, string>): void {
  const absolutePath = resolve(filePath);

  const lines = [
    '# Orchestrator Environment Configuration',
    '# Generated by orchestrator CLI',
    '',
  ];

  for (const [key, value] of Object.entries(template)) {
    lines.push(`${key}=${value}`);
  }

  lines.push('');
  writeFileSync(absolutePath, lines.join('\n'), 'utf-8');
}

/**
 * Get the default .env file path.
 */
export function getDefaultEnvPath(): string {
  return resolve(process.cwd(), '.env');
}

/**
 * Common environment variable keys.
 */
export const ENV_KEYS = {
  // LiteLLM
  LITELLM_BASE_URL: 'LITELLM_BASE_URL',
  LITELLM_API_KEY: 'LITELLM_API_KEY',

  // Direct providers
  OPENAI_API_KEY: 'OPENAI_API_KEY',
  ANTHROPIC_API_KEY: 'ANTHROPIC_API_KEY',
  GOOGLE_AI_API_KEY: 'GOOGLE_AI_API_KEY',

  // Search
  TAVILY_API_KEY: 'TAVILY_API_KEY',
  BRAVE_SEARCH_API_KEY: 'BRAVE_SEARCH_API_KEY',

  // Database
  DATABASE_PATH: 'DATABASE_PATH',

  // Server
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  LOG_LEVEL: 'LOG_LEVEL',
} as const;